#!/usr/bin/env python3
"""
seed_billboard_d1.py
Generates SQL to upsert Billboard Year-End Hot 100 (2000-2020) tracks into kapiko D1.

Strategy:
  - For each billboard track, generate a slug (title-artist, lowercase, hyphenated)
  - INSERT OR IGNORE for new tracks (preserves existing Spotify-sourced data)
  - Always UPDATE billboard_year and billboard_rank on any matching track
  - Matching is: exact slug match first, then LOWER(name)/LOWER(artists) fuzzy match
  - For brand-new tracks (no Spotify data), insert with placeholder audio features

Usage:
  python3 seed_billboard_d1.py
  # Outputs: seed_billboard.sql in ~/kapiko/api/
  # Then run: cd ~/kapiko/api && npx wrangler d1 execute kapiko-db --remote --file ./seed_billboard.sql
"""

import json
import re
import os

BILLBOARD_JSON = os.path.expanduser('~/kapiko/top-100-by-year-2000-2020.json')
OUTPUT_SQL = os.path.expanduser('~/kapiko/api/seed_billboard.sql')

# Placeholder audio features for tracks with no Spotify data
PLACEHOLDER = {
    'album': None,
    'genre_id': None,
    'popularity': 50,
    'duration_ms': 210000,
    'tempo': 120.0,
    'energy': 0.5,
    'valence': 0.5,
    'loudness': -8.0,
    'acousticness': 0.3,
    'danceability': 0.6,
    'instrumentalness': 0.01,
    'speechiness': 0.05,
    'liveness': 0.15,
    'key': 0,
    'mode': 1,
    'time_signature': 4,
}


def make_slug(title, artist):
    """Match the slug pattern from gen_billboard_2000.py"""
    primary = re.split(r'\s+feat\w*\s+|\s+ft\.?\s+|\s+with\s+', artist, flags=re.IGNORECASE)[0].strip()
    return re.sub(r'[^a-z0-9]+', '-', (title + '-' + primary).lower()).strip('-')


def escape_sql(val):
    if val is None:
        return 'NULL'
    if isinstance(val, str):
        return "'" + val.replace("'", "''") + "'"
    return str(val)


def main():
    with open(BILLBOARD_JSON) as f:
        data = json.load(f)

    years = data['years']
    all_tracks = []
    for year_str, tracks in years.items():
        year = int(year_str)
        for track in tracks:
            all_tracks.append({
                'year': year,
                'rank': track['rank'],
                'title': track['title'],
                'artist': track['artist'],
                'slug': make_slug(track['title'], track['artist']),
            })

    print(f"Loaded {len(all_tracks)} billboard tracks across {len(years)} years")

    statements = []
    statements.append("-- Billboard Year-End Hot 100 (2000-2020) seeder")
    statements.append("-- Generated by seed_billboard_d1.py")
    statements.append("-- Strategy: INSERT OR IGNORE new tracks, always UPDATE billboard columns")
    statements.append("")

    # Dedupe: a track might appear in multiple years (rare but possible)
    # We keep the earliest year / best rank for the main insert, but we store per-year data
    # Actually the task says billboard_year is singular — for now, use earliest occurrence
    # (Multiple years would require a junction table, outside scope)

    seen_slugs = {}  # slug -> first occurrence
    for t in all_tracks:
        slug = t['slug']
        if slug not in seen_slugs:
            seen_slugs[slug] = t
        # If seen again, keep whichever has better rank (lower number)
        elif t['rank'] < seen_slugs[slug]['rank']:
            seen_slugs[slug] = t

    unique_tracks = list(seen_slugs.values())
    print(f"Unique slugs: {len(unique_tracks)}")

    # For each unique track: INSERT OR IGNORE first, then UPDATE billboard columns
    # This means:
    #   - Existing Spotify tracks get their billboard_year/rank updated
    #   - New tracks get inserted with placeholder audio features
    #   - No existing Spotify data is overwritten

    inserts = []
    updates = []

    for t in all_tracks:
        slug = t['slug']
        title_esc = escape_sql(t['title'])
        artist_esc = escape_sql(t['artist'])

        # INSERT OR IGNORE — only inserts if id doesn't exist
        p = PLACEHOLDER
        insert = (
            f"INSERT OR IGNORE INTO tracks "
            f"(id, name, artists, album, genre_id, popularity, duration_ms, tempo, energy, valence, "
            f"loudness, acousticness, danceability, instrumentalness, speechiness, liveness, "
            f"key, mode, time_signature, source, billboard_year, billboard_rank, created_at) VALUES ("
            f"{escape_sql(slug)}, "
            f"{title_esc}, "
            f"{artist_esc}, "
            f"{escape_sql(p['album'])}, "
            f"{escape_sql(p['genre_id'])}, "
            f"{p['popularity']}, "
            f"{p['duration_ms']}, "
            f"{p['tempo']}, "
            f"{p['energy']}, "
            f"{p['valence']}, "
            f"{p['loudness']}, "
            f"{p['acousticness']}, "
            f"{p['danceability']}, "
            f"{p['instrumentalness']}, "
            f"{p['speechiness']}, "
            f"{p['liveness']}, "
            f"{p['key']}, "
            f"{p['mode']}, "
            f"{p['time_signature']}, "
            f"'billboard', "
            f"{t['year']}, "
            f"{t['rank']}, "
            f"datetime('now')"
            f");"
        )
        inserts.append(insert)

        # UPDATE billboard columns by exact slug match (covers both new inserts and existing Spotify tracks with same slug)
        update = (
            f"UPDATE tracks SET billboard_year = {t['year']}, billboard_rank = {t['rank']} "
            f"WHERE id = {escape_sql(slug)};"
        )
        updates.append(update)

        # Also update by exact name match (no LIKE, avoids complexity errors)
        update_name = (
            f"UPDATE tracks SET billboard_year = {t['year']}, billboard_rank = {t['rank']} "
            f"WHERE LOWER(name) = LOWER({title_esc});"
        )
        updates.append(update_name)

    statements.extend(inserts)
    statements.append("")
    statements.append("-- Update billboard columns on all matching tracks (including existing Spotify tracks)")
    statements.extend(updates)

    sql_content = '\n'.join(statements)

    with open(OUTPUT_SQL, 'w') as f:
        f.write(sql_content)

    total_lines = len(statements)
    print(f"Wrote {total_lines} SQL statements to {OUTPUT_SQL}")
    print(f"  INSERT OR IGNORE statements: {len(inserts)}")
    print(f"  UPDATE statements: {len(updates)} (slug + fuzzy per track)")
    print(f"\nNext step:")
    print(f"  cd ~/kapiko/api && npx wrangler d1 execute kapiko-db --remote --file ./seed_billboard.sql")


if __name__ == '__main__':
    main()
